version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - app:/usr/src/app
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - nginx

  db:
    image: postgres:12.0-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 1337:80
    depends_on:
      - parcel

  parcel:
    build:
      context: .
      dockerfile: Dockerfile.parcel
    command: parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - app:/usr/src/app



volumes:
  postgres_data:
  static_volume:
  app:
  media_volume:
