# Generated by Django 3.2 on 2021-08-14 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='request_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата запроса к геокодеру'),
        ),
    ]
