# Generated by Django 3.2 on 2021-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20210804_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNANSWERED', 'Не обработан'), ('EN_ROUTE', 'В пути'), ('COMPLETED', 'Выполнен')], default='UNANSWERED', max_length=12, verbose_name='статус'),
        ),
    ]
