# Generated by Django 3.2 on 2021-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(related_name='orders', to='foodcartapp.Restaurant', verbose_name='ресторан'),
        ),
    ]
