# Generated by Django 3.2 on 2021-08-06 15:20

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, validators=[django.core.validators.MaxLengthValidator(12)], verbose_name='контактный телефон'),
        ),
    ]
